import { useCallback, useEffect, useState } from 'react';
import { Download, Printer, Search, Upload } from 'lucide-react';
import { exportCustomerPartNumbers, getCustomerPartNumbers, getCustomers, importCustomerPartNumbers } from '../services/api';

export default function CustomerPartNumbers() {
  const [rows, setRows] = useState([]); const [customers, setCustomers] = useState([]); const [summary, setSummary] = useState({});
  const [search, setSearch] = useState(''); const [customerId, setCustomerId] = useState(''); const [file, setFile] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const res = await getCustomerPartNumbers({ search, customer_id: customerId }); setRows(res.data?.data || []); setSummary(res.data?.summary || {}); } catch (e) { setError(e.response?.data?.message || 'Data gagal dimuat.'); } finally { setLoading(false); } }, [search, customerId]);
  useEffect(() => { getCustomers().then(res => setCustomers(res.data?.data || [])).catch(() => { }); }, []); useEffect(() => { const t = setTimeout(load, 300); return () => clearTimeout(t); }, [load]);
  const importFile = async () => {
    if (!file) return setError('Pilih file Excel terlebih dahulu.');
    try { await importCustomerPartNumbers(file); setFile(null); setError(''); load(); } catch (e) { setError(e.response?.data?.message || 'Import gagal.'); }
  };
  const download = async () => { const res = await exportCustomerPartNumbers(); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([res.data])); a.download = 'data-customer.csv'; a.click(); URL.revokeObjectURL(a.href); };
  return <div className="p-6 space-y-5 max-w-7xl mx-auto w-full">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold text-slate-800">Data Customer</h2><p className="text-sm text-slate-500">Database part number dan item berdasarkan customer.</p></div><div className="flex gap-2"><label className="cursor-pointer flex items-center gap-2 px-3 py-2 rounded-xl bg-emerald-600 text-white text-sm"><Upload className="w-4 h-4" />Import Excel<input type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={e => setFile(e.target.files[0])} /></label><button onClick={importFile} disabled={!file} className="px-3 py-2 rounded-xl bg-blue-600 text-white text-sm disabled:opacity-50">Proses Import</button><button onClick={download} className="flex items-center gap-2 px-3 py-2 rounded-xl bg-slate-700 text-white text-sm"><Download className="w-4 h-4" />Export Excel</button><button onClick={() => window.print()} className="flex items-center gap-2 px-3 py-2 rounded-xl border text-sm"><Printer className="w-4 h-4" />PDF / Print</button></div></div>
      {file && <div className="text-xs text-blue-600">File dipilih: {file.name}</div>}{error && <div className="p-3 rounded-xl bg-red-50 text-red-700 text-sm">{error}</div>}
      <div className="grid md:grid-cols-2 gap-4"><div className="bg-white rounded-2xl border p-5"><p className="text-xs text-slate-500">Total Customer</p><p className="text-3xl font-bold text-blue-600">{summary.total_customer || 0}</p></div><div className="bg-white rounded-2xl border p-5"><p className="text-xs text-slate-500">Total Part Number</p><p className="text-3xl font-bold text-blue-600">{summary.total_part_number || 0}</p></div></div>
      <div className="bg-white rounded-2xl border p-4 flex-wrap gap-3"><div className="relative flex-1 min-w-64"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search Part Number / Item Description" className="w-full border rounded-xl pl-9 pr-3 py-2 text-sm" /></div><select value={customerId} onChange={e => setCustomerId(e.target.value)} className="border rounded-xl px-3 py-2 text-sm"><option value="">Semua Customer</option>{customers.map(c => <option key={c.id} value={c.id}>{c.customer_name}</option>)}</select></div>
      <div className="bg-white rounded-2xl border overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{['Customer', 'Part Number', 'Item Description', 'Harga Jual', 'Status'].map(h => <th key={h} className="text-left p-4">{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan="5" className="p-8 text-center text-slate-400">Memuat data...</td></tr> : rows.map(r => <tr key={r.id} className="border-t"><td className="p-4 font-medium">{r.customer?.customer_name || '-'}</td><td className="p-4 font-mono">{r.part_number}</td><td className="p-4">{r.item_description || '-'}</td><td className="p-4">{r.selling_price ? Number(r.selling_price).toLocaleString('id-ID') : '-'}</td><td className="p-4">{r.status}</td></tr>)}{!loading && !rows.length && <tr><td colSpan="5" className="p-8 text-center text-slate-400">Belum ada data.</td></tr>}</tbody></table></div>
    </div>;
}
