import { useCallback, useEffect, useState } from 'react';
import { getBoms, getProductions, createProduction, getWarehouses } from '../services/api';

export default function Production() {
  const [rows, setRows] = useState([]); const [boms, setBoms] = useState([]); const [warehouses, setWarehouses] = useState([]);
  const [form, setForm] = useState({ document_number: `PROD-${Date.now()}`, bom_id: '', production_date: new Date().toISOString().slice(0, 10), quantity: 1, warehouse_id: '', notes: '' }); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { try { const [b, p, w] = await Promise.all([getBoms(), getProductions(), getWarehouses()]); setBoms(b.data?.data || []); setRows(p.data?.data || []); setWarehouses(w.data?.data || []); } catch (e) { setError(e.response?.data?.message || 'Data produksi gagal dimuat.'); } }, []);
  useEffect(() => { load(); }, [load]);
  const submit = async (e) => {
    e.preventDefault(); setError(''); setMessage('');
    try { await createProduction({ ...form, quantity: Number(form.quantity), warehouse_id: form.warehouse_id || null }); setMessage('Produksi selesai. Component berkurang dan produk jadi bertambah.'); setForm({ ...form, document_number: `PROD-${Date.now()}`, bom_id: '', quantity: 1 }); await load(); }
    catch (e) { setError(e.response?.data?.message || Object.values(e.response?.data?.errors || {}).flat()[0] || 'Produksi gagal diproses.'); }
  };
  return <div className="p-6 max-w-7xl mx-auto w-full space-y-5"><div><h2 className="text-2xl font-bold">Produksi</h2><p className="text-sm text-slate-500">Konsumsi component dan penerimaan produk jadi melalui Inventory Stock Service.</p></div>{error && <div className="p-3 rounded-lg bg-red-50 text-red-700 text-sm">{error}</div>}{message && <div className="p-3 rounded-lg bg-emerald-50 text-emerald-700 text-sm">{message}</div>}<form onSubmit={submit} className="bg-white border rounded-2xl p-5 grid md:grid-cols-5 gap-3"><input required value={form.document_number} onChange={e => setForm({ ...form, document_number: e.target.value })} placeholder="Nomor produksi" className="border rounded-lg px-3 py-2 text-sm" /><input required type="date" value={form.production_date} onChange={e => setForm({ ...form, production_date: e.target.value })} className="border rounded-lg px-3 py-2 text-sm" /><select required value={form.bom_id} onChange={e => setForm({ ...form, bom_id: e.target.value })} className="border rounded-lg px-3 py-2 text-sm"><option value="">Pilih BOM</option>{boms.map(b => <option key={b.id} value={b.id}>{b.document_number} — {b.product?.name}</option>)}</select><input required min="0.001" type="number" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })} placeholder="Qty hasil" className="border rounded-lg px-3 py-2 text-sm" /><select value={form.warehouse_id} onChange={e => setForm({ ...form, warehouse_id: e.target.value })} className="border rounded-lg px-3 py-2 text-sm"><option value="">Warehouse Utama</option>{warehouses.map(w => <option key={w.id} value={w.id}>{w.code} — {w.name}</option>)}</select><button className="md:col-span-5 px-4 py-2 rounded-lg bg-blue-600 text-white text-sm">Selesaikan Produksi</button></form><div className="bg-white border rounded-2xl overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Dokumen</th><th className="p-3 text-left">Tanggal</th><th className="p-3 text-left">BOM</th><th className="p-3 text-left">Qty</th><th className="p-3 text-left">Status</th></tr></thead><tbody>{rows.map(r => <tr key={r.id} className="border-t"><td className="p-3 font-mono">{r.document_number}</td><td className="p-3">{r.production_date}</td><td className="p-3">{r.bom?.document_number || '-'}</td><td className="p-3">{r.quantity}</td><td className="p-3">{r.status}</td></tr>)}{!rows.length && <tr><td colSpan="5" className="p-8 text-center text-slate-400">Belum ada produksi.</td></tr>}</tbody></table></div></div>;
}
